version: "3"
services:
 mysql:
  image: mysql:5.7
  deploy:
   resources:
    limits:
      cpus: '0.15'
      #memory: 180M
   placement:
    constraints: [node.role == manager]
  ports:
    - ${MYSQL_PORT}:3306
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  networks: 
    - ${APPLICATION_NETWORK}
  volumes:
    - "./data:/var/lib/mysql"
 phpmyadmin_application:
  image: phpmyadmin/phpmyadmin
  deploy:
   placement:
    constraints: [node.role == manager]
  networks:
   - ${APPLICATION_NETWORK}
  environment:
   PMA_HOST: mysql
   PMA_PORT: 3306
  ports:
   - ${PHPMYADMIN_PORT}:80
  volumes: 
   - /sessions
 application:
  image: leolegends/microservices_php:stable
  deploy:
   replicas: 1
  # resources:
   # limits:
   #  cpus: "0.1"
   #  memory: 50M  
   restart_policy:
    condition: on-failure
  ports: 
   - ${HOST_PORT}:80
  volumes:
   - ${SERVICE_LOCATION}:/app
  environment:
   WEB_DOCUMENT_ROOT: /app/public
  networks:
   - ${APPLICATION_NETWORK}
networks: 
 app_network:
